version: '3'

services:
  web:
      build: .
      command: python manage.py runserver 0.0.0.0:8000
      container_name: bimamitra_postgre_webapp
      ports: 
      - 8000:8000
      depends_on:
      - db
  db:
    image: postgres:latest
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=test_database
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=1234
    container_name: bimamitra_postgre_database
    ports:
      - 5432:5432