# Generated by Django 5.0 on 2024-01-02 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application_insure', '0003_delete_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUs',
        ),
    ]
