# Generated by Django 5.0 on 2024-01-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_insure', '0005_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='YourFixedUsername', max_length=255)),
                ('user_input', models.CharField(max_length=255)),
                ('response', models.CharField(max_length=1255)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
