# Generated by Django 5.0 on 2024-01-16 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_insure', '0006_searchrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchrecord',
            name='response',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='searchrecord',
            name='user_input',
            field=models.CharField(max_length=1255),
        ),
        migrations.AlterField(
            model_name='searchrecord',
            name='username',
            field=models.CharField(default='admin', max_length=255),
        ),
    ]
